// Expanded Mapping of Clothing Items to Occasions
const occasionDataset = {
    // Tops
    "t-shirt": "Casual",
    "jersey": "Sport",
    "sports jersey": "Sport",
    "football jersey": "Sport",
    "basketball jersey": "Sport",
    "soccer jersey": "Sport",
    "rugby jersey": "Sport",
    "sweatshirt": "Casual",
    "shirt": "Smart",
    "blouse": "Smart",
    "tank top": "Casual",
    "polo shirt": "Smart",
    "hoodie": "Casual",
    "cardigan": "Smart",
    "sweater": "Smart",
    "tunic": "Smart",
    "vest": "Smart",
    "kimono": "Smart",
    "crop top": "Casual",
    "thermal top": "Casual",
    "long sleeve shirt": "Smart",
    "short sleeve shirt": "Casual",
    "bodysuit": "Smart",
    "bolero": "Smart",
    "camisole": "Casual",
    "caftan": "Smart",
    "chemise": "Casual",
    "cape": "Smart",
    "blazer": "Formal",
    "bomber jacket": "Casual",
  
    // Bottoms
    "jeans": "Casual",
    "shorts": "Sport",
    "swimming shorts": "Sport",
    "skirt": "Smart",
    "trousers": "Formal",
    "cargo pants": "Casual",
    "sweatpants": "Sport",
    "leggings": "Casual",
    "chinos": "Smart",
    "culottes": "Smart",
    "joggers": "Sport",
    "bike shorts": "Sport",
    "denim skirt": "Casual",
    "cargo shorts": "Casual",
    "pencil skirt": "Smart",
    "palazzo pants": "Smart",
    "bermuda shorts": "Casual",
    "capris": "Casual",
    "breeches": "Formal",
    "bloomers": "Casual",
    "jean": "Smart",
  
    // Footwear
    "sneaker": "Sport",
    "running shoe": "Sport",
    "football shoe": "Sport",
    "cleat": "Sport",
    "boot": "Casual",
    "high heel": "Formal",
    "flat": "Smart",
    "loafer": "Formal",
    "sandal": "Casual",
    "flip-flop": "Casual",
    "oxford": "Formal",
    "dress shoe": "Formal",
    "trainer": "Sport",
    "ankle boot": "Smart",
    "combat boot": "Casual",
    "moccasin": "Casual",
    "slipper": "Casual",
    "ballet flat": "Smart",
    "wedge": "Formal",
    "clogs": "Casual",
    "espadrille": "Casual",
    "thong sandal": "Casual",
    "platform shoe": "Formal",
  };
  


export {occasionDataset}